# Generated by Django 5.2.8 on 2025-12-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='address',
            field=models.CharField(default='القيمة الافتراضية', max_length=200),
        ),
        migrations.AddField(
            model_name='storemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='storemodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
