# Generated by Django 5.2.8 on 2025-12-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storemodel_address_storemodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='doc',
            field=models.FileField(null=True, upload_to='document'),
        ),
        migrations.AddField(
            model_name='storemodel',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
