# Generated by Django 5.2.8 on 2025-12-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_storemodel_doc_storemodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'male')], max_length=1, null=True),
        ),
    ]
