# Generated by Django 5.2.8 on 2025-12-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_storemodel_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storemodel',
            options={'managed': True, 'verbose_name': 'ModelName', 'verbose_name_plural': 'ModelNames'},
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='address',
            field=models.CharField(default='القيمة الافتراضية', max_length=50),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterModelTable(
            name='storemodel',
            table='StoreModel',
        ),
    ]
