# Generated by Django 5.2.8 on 2025-12-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_alter_storemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('z', 'z')], max_length=1),
        ),
    ]
